name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment.yml
        init-shell: >-
          bash
          powershell
        cache-environment: true
        post-cleanup: 'all'
    - name: Fix RDKit
      run: |
        wget https://gist.githubusercontent.com/shirte/e1734e51dbc72984b2d918a71b68c25b/raw/ae4afece11980f5d7da9e7668a651abe349c357a/rdkit_installation_fix.sh
        chmod +x rdkit_installation_fix.sh
        ./rdkit_installation_fix.sh cyplebrity
      shell: micromamba-shell {0}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e git+https://github.com/chembl/FPSim2.git@0.2.8#egg=fpsim2
        pip install .[test,dev]
      shell: micromamba-shell {0}
    - name: Test with pytest
      run: |
        pytest
      shell: micromamba-shell {0}
          